## Broadcasting and Vectorized Operations

In [1]:
import numpy as np

In [2]:
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [4]:
a + 10

array([10, 11, 12, 13])

In [6]:
a * 5

array([ 0,  5, 10, 15])

In [7]:
a += 10

In [8]:
a

array([10, 11, 12, 13])

In [9]:
l = [0, 1, 2, 3]

In [10]:
[i*10 for i in l]

[0, 10, 20, 30]

In [11]:
a = np.arange(4)

In [12]:
b = np.array([10, 10, 10, 10])

In [13]:
a+b

array([10, 11, 12, 13])

In [14]:
a*b

array([ 0, 10, 20, 30])

## Boolean Arrays

In [15]:
a = np.arange(4)

In [16]:
a

array([0, 1, 2, 3])