In [2]:
import numpy as np

In [3]:
n = 5

In [4]:
n ** 5

3125

In [5]:
np.int8

numpy.int8

In [12]:
arr1 = np.array([1,5,6,9,45,-4])

In [13]:
arr2 = np.array([0.1, 0.8, 0.9, -0.45])

In [21]:
arr3 = np.array([4, -2, -45, 47, 129], dtype=np.int8)

In [9]:
arr1[0]

1

In [17]:
arr2[2]

0.9

## Array Types

In [15]:
arr1

array([ 1,  5,  6,  9, 45, -4])

In [16]:
arr1.dtype

dtype('int64')

In [18]:
arr2.dtype

dtype('float64')

In [22]:
arr3.dtype

dtype('int8')

In [23]:
arr4 = np.array(['a', 'b', 'c'])

In [24]:
arr4.dtype

dtype('<U1')

## Dimensions and Shapes

In [25]:
A = np.array([
    [45, 58, 1],
    [-55, -14, -21]
])

In [26]:
A.shape

(2, 3)

In [28]:
A.dtype

dtype('int64')

In [27]:
A.nbytes

48

In [29]:
A.size

6

In [34]:
B = np.array([
    [
        [1, 2, 3],
        [-1, -2, -3]
    ],
    [
        [11, 22, 33],
        [-11, -22, -33]
    ]
])

In [35]:
B.shape

(2, 2, 3)

In [37]:
B.ndim

3

## Indexing and Slicing of Matrices

In [38]:
# Square matrix
A = np.array([
    [1,2,3], #0
    [4,5,6], #1
    [7,8,9]  #2
])

In [39]:
A[2]

array([7, 8, 9])

In [40]:
A[0][1]

2

In [41]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
A[:1][0:]

array([[1, 2, 3]])

In [45]:
A[2] = np.array([10,10,10])

In [46]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 10, 10]])

In [57]:
A[0] = -20

In [58]:
A

array([[-20, -20, -20],
       [  4,   5,   6],
       [ 10,  10,  10]])

## Summary Statistics

In [59]:
a = np.array([5, 9, -45, -4, 54, 1])

In [60]:
a.sum()

20

In [61]:
a.mean()

3.3333333333333335

In [62]:
a.var()

832.8888888888888

In [63]:
A.sum()

-15

In [65]:
A.mean()

-1.6666666666666667

In [66]:
A.sum(axis=1) # Per row

array([-60,  15,  30])

In [67]:
A.sum(axis=0) # Per column

array([-6, -5, -4])