## Boolean Arrays
(Also called masks)

In [1]:
import numpy as np

In [2]:
a = np.arange(4)

In [3]:
a[[0, -1]]

array([0, 3])

In [5]:
a[[True, False, False, True]]

array([0, 3])

In [6]:
a >= 2

array([False, False,  True,  True])

In [8]:
a[a <= 2]

array([0, 1, 2])

In [9]:
a.mean()

1.5

In [10]:
a[~(a > a.mean())]

array([0, 1])

In [11]:
a[(a == 1) | (a == 2)]

array([1, 2])

In [12]:
a[(a <= 1) & (a%2 == 0)]

array([0])

In [13]:
 A = np.random.randint(100, size = (3,3))

In [14]:
A

array([[27,  1, 13],
       [38, 48, 63],
       [ 7, 71, 54]])

In [15]:
A > 20

array([[ True, False, False],
       [ True,  True,  True],
       [False,  True,  True]])

In [16]:
A[A > 20]

array([27, 38, 48, 63, 71, 54])