## Linear Algebra

In [12]:
import numpy as np
import sys

In [3]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [4]:
B = np.array([
    [6, 5],
    [4,3],
    [2,1]
])

In [5]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [7]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [8]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [9]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## Size of Objects in Memory
### Int, floats

In [27]:
# An integer in Python is >= 24 bytes
sys.getsizeof(0)

24

In [28]:
sys.getsizeof(10**100)

72

In [29]:
# Numpy size is much smalles
np.dtype(int).itemsize

8

In [30]:
np.dtype(float).itemsize

8

In [32]:
np.dtype(np.int8).itemsize

1

### Lists

In [33]:
# A one-element list
sys.getsizeof([0])

64

In [34]:
# An array of one element in numpy
np.array([0]).nbytes

8

### Performance

In [41]:
l = list(range(1000000))

In [42]:
a = np.arange(1000000)

In [43]:
%time np.sum(a**2)

CPU times: user 966 µs, sys: 3.54 ms, total: 4.5 ms
Wall time: 3.6 ms


333332833333500000

In [44]:
%time sum([x ** 2 for x in l])

CPU times: user 340 ms, sys: 1.63 ms, total: 342 ms
Wall time: 347 ms


333332833333500000

## Useful Numpy Functions

### **random**

In [47]:
np.random.random(size = 4)

array([0.10006085, 0.22752115, 0.17994168, 0.95211098])

In [48]:
np.random.normal(size = 4)

array([ 0.68800847, -0.09045928,  2.17657624,  0.506214  ])

In [50]:
np.random.rand(4, 4)

array([[0.29425689, 0.09013983, 0.38157114, 0.58810391],
       [0.76881644, 0.39626562, 0.14266296, 0.31147736],
       [0.13935389, 0.38919934, 0.19055413, 0.36732791],
       [0.36859901, 0.10351006, 0.51954853, 0.97183795]])

### **arange**

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [54]:
np.arange(0,  5, .5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### **reshape**

In [55]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### **linspace**

In [57]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [59]:
np.linspace(0, 1, 30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

In [60]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### **zeros, ones, empty**

In [61]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [64]:
np.ones(3)

array([1., 1., 1.])

In [65]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
np.empty(5)

array([4.940656e-324, 9.881313e-324, 4.940642e-318, 4.940647e-318,
       4.940652e-318])

In [71]:
np.empty((2,3))

array([[0.000000e+000, 4.940656e-324, 9.881313e-324],
       [4.940642e-318, 4.940647e-318, 4.940652e-318]])

### **identity** and **eye**

In [72]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [76]:
np.eye(8, 4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
np.eye(8, 4, k = -3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [78]:
"Hello World"[6]

'W'